name = "fortfem"
version = "0.1.0"
license = "license"
author = "Christopher Albert"
maintainer = "albert@tugraz.at"
copyright = "Copyright 2025, Christopher Albert"
description = "A modern Fortran finite element library designed for ease of use, inspired by FreeFEM and FEniCS"
homepage = "https://github.com/itpplasma/fortfem"
keywords = ["finite-elements", "pde", "scientific-computing", "fortran", "fem"]
categories = ["science"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["lapack", "umfpack", "amd", "cholmod", "suitesparseconfig"]

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[extra.ford]
project = "FortFEM"
summary = "A modern Fortran finite element library"
version = "0.1.0"
email = "albert@tugraz.at"
github = "https://github.com/itpplasma/fortfem"
website = "https://github.com/itpplasma/fortfem"
license = "MIT"
src_dir = "src"
output_dir = "build/doc"
page_dir = "doc"
graph_maxnodes = 32
graph_maxdepth = 4
source = true
proc_internals = true
sort = "permission-alpha"
print_creation_date = true
creation_date = "%Y-%m-%d %H:%M %z"
md_extensions = ["markdown.extensions.toc", "markdown.extensions.smarty", "markdown.extensions.fenced_code", "markdown.extensions.codehilite"]

[dependencies]
fortplot = { git = "https://github.com/lazy-fortran/fortplot.git" }
blas = "*"

[dev-dependencies]
test-drive = { git = "https://github.com/fortran-lang/test-drive.git" }


